[tool.poetry]
name = "atnacha"
version = "0.1.0"
description = "NACHA file generation"
authors = ["Tyler Matteson <tyler@agritheory.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-coverage = "^0.0"
tox-poetry-installer = {extras = ["poetry"], version = "^0.8.4"}
tox-gh-actions = "^2.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

packages = [
    { include = "atnacha" },
]

[tool.tox]
legacy_tox_ini = """

[tox]
envlist = py38, py39, py310, mypy
isolated_build = true

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310, mypy

[testenv]
description = Check syntax and run tests
require_locked_deps = true
install_dev_deps = true
commands =
    poetry run black ./
    poetry run pytest --cov=./ --cov-report=xml
"""