import datetime
from dataclasses import dataclass, field

@dataclass
class NACHAFile:
    priority_code: int = ...
    immediate_destination: str = ...
    immediate_origin: str = ...
    file_creation_date: datetime.date = ...
    file_creation_time: datetime.time = ...
    file_id_modifier: str = ...
    blocking_factor: int = ...
    format_code: int = ...
    immediate_destination_name: str = ...
    immediate_origin_name: str = ...
    reference_code: str = ...
    batches: list = field(default_factory=list)
    @property
    def record_size(self) -> int: ...
    @property
    def block_count(self) -> int: ...
    @property
    def entry_addenda_account(self) -> int: ...
    @property
    def entry_hash(self) -> str: ...
    @property
    def total_credit(self) -> int: ...
    @property
    def total_debit(self) -> int: ...
    @property
    def header(self) -> str: ...
    @property
    def control(self) -> str: ...
    def batch_number(self, batch: ACHBatch) -> str: ...
    def __call__(self) -> str: ...

@dataclass
class ACHBatch:
    service_class_code: int = ...
    company_name: str = ...
    company_discretionary_data: str = ...
    company_id: str = ...
    standard_class_code: str = ...
    company_entry_description: str = ...
    company_descriptive_date: str = ...
    effective_entry_date: datetime.date = ...
    settlement_date: str = ...
    originator_status_code: str = ...
    originating_dfi_id: str = ...
    entries: list = field(default_factory=list)
    @property
    def header(self) -> str: ...
    @property
    def control(self) -> str: ...
    @property
    def total_credit(self) -> int: ...
    @property
    def total_debit(self) -> int: ...
    @property
    def entry_hash(self) -> str: ...
    def trace_number(self, entry) -> str: ...
    def __call__(self, batch_number: int = 1) -> str: ...

@dataclass
class ACHEntry:
    transaction_code: int = ...
    receiving_dfi_identification: str = ...
    dfi_account_number: str = ...
    amount: int = ...
    individual_id_number: str = ...
    individual_name: str = ...
    discretionary_data: str = ...
    addenda_record_indicator: str = ...
    batch: ACHBatch | None = ...
    @property
    def check_digit(self) -> int: ...
    def __call__(self) -> str: ...
